version: '3.8'

services:
  rag-api:
    build: .
    ports:
      - "8000:8000"
    environment:
      # OpenAI Configuration
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      
      # Azure Cosmos DB Configuration
      - AZURE_COSMO_URL=${AZURE_COSMO_URL}
      - AZURE_COSMO_KEY=${AZURE_COSMO_KEY}
      
      # Application Configuration
      - PYTHONPATH=/app
    volumes:
      # Optional: Mount logs directory for persistent logging
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - rag-network

networks:
  rag-network:
    driver: bridge
